In [1]:
import numpy as np

In [2]:
array_1D=np.array([1,2,3,4,5])
print(array_1D)

[1 2 3 4 5]


In [3]:
type(array_1D)

numpy.ndarray

In [4]:
array_1D

array([1, 2, 3, 4, 5])

In [5]:
array_1D.ndim

1

In [6]:
arry_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arry_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
arry_2d.ndim

2

In [8]:
arry_2d.size

8

In [9]:
arry_2d.dtype

dtype('int32')

In [10]:
arry_2d.shape


(2, 4)

In [14]:
ones=np.ones((3,4),dtype=bool)
print(ones)
ones.dtype

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


dtype('bool')

In [20]:
zeros=np.zeros((4,5), dtype=str)
print(zeros)
zeros.dtype

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


dtype('<U1')

In [25]:
string='string'
print(bool(string))

True


In [24]:
empty=np.empty((3,3),dtype=int)
print(empty)

[[          0           1           0]
 [        492        1176           0]
 [        768         144 -1132585504]]
